/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMultichainERC20 } from "./IMultichainERC20";
export type { MultichainFacet } from "./MultichainFacet";
