/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  TestViolationsEvents,
  TestViolationsEventsInterface,
} from "../../TestViolationsEvents.sol/TestViolationsEvents";

const _abi = [
  {
    type: "function",
    name: "emitEvent",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "SomeEvent",
    inputs: [
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b50609e80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b0cb83914602a575b5f5ffd5b60306032565b005b604051607b81527f379340f64b65a8890c7ea4f6d86d2359beaf41080f36a7ea64b78a2c06eee3f09060200160405180910390a156fea264697066735822122044119e7129b7740986d69f7bd08cb38ce178511e1db647191ea5acc96539aa1c64736f6c634300081d0033";

type TestViolationsEventsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestViolationsEventsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestViolationsEvents__factory extends ContractFactory {
  constructor(...args: TestViolationsEventsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TestViolationsEvents> {
    return super.deploy(overrides || {}) as Promise<TestViolationsEvents>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TestViolationsEvents {
    return super.attach(address) as TestViolationsEvents;
  }
  override connect(signer: Signer): TestViolationsEvents__factory {
    return super.connect(signer) as TestViolationsEvents__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestViolationsEventsInterface {
    return new utils.Interface(_abi) as TestViolationsEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestViolationsEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TestViolationsEvents;
  }
}
