/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestInterface__factory } from "./TestInterface__factory";
export { TestViolationsNaming__factory } from "./TestViolationsNaming__factory";
