/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IAccessGate, IAccessGateInterface } from "../IAccessGate";

const _abi = [
  {
    type: "function",
    name: "isAllowed",
    inputs: [
      {
        name: "_account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isSanctioned",
    inputs: [
      {
        name: "_account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isTransferable",
    inputs: [
      {
        name: "_from",
        type: "address",
        internalType: "address",
      },
      {
        name: "_to",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IAccessGate__factory {
  static readonly abi = _abi;
  static createInterface(): IAccessGateInterface {
    return new utils.Interface(_abi) as IAccessGateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccessGate {
    return new Contract(address, _abi, signerOrProvider) as IAccessGate;
  }
}
