/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISyncSwapV2Vault,
  ISyncSwapV2VaultInterface,
} from "../ISyncSwapV2Vault";

const _abi = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "payable",
  },
] as const;

export class ISyncSwapV2Vault__factory {
  static readonly abi = _abi;
  static createInterface(): ISyncSwapV2VaultInterface {
    return new utils.Interface(_abi) as ISyncSwapV2VaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISyncSwapV2Vault {
    return new Contract(address, _abi, signerOrProvider) as ISyncSwapV2Vault;
  }
}
