/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAcrossRouter,
  IAcrossRouterInterface,
} from "../../../src/Interfaces/IAcrossRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "l1Recipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "l2Token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "slowRelayFeePct",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "instantRelayFeePct",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "quoteTimestamp",
        type: "uint64",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IAcrossRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IAcrossRouterInterface {
    return new utils.Interface(_abi) as IAcrossRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAcrossRouter {
    return new Contract(address, _abi, signerOrProvider) as IAcrossRouter;
  }
}
