/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ILiFi {
  export type BridgeDataStruct = {
    transactionId: PromiseOrValue<BytesLike>;
    bridge: PromiseOrValue<string>;
    integrator: PromiseOrValue<string>;
    referrer: PromiseOrValue<string>;
    sendingAssetId: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
    minAmount: PromiseOrValue<BigNumberish>;
    destinationChainId: PromiseOrValue<BigNumberish>;
    hasSourceSwaps: PromiseOrValue<boolean>;
    hasDestinationCall: PromiseOrValue<boolean>;
  };

  export type BridgeDataStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean
  ] & {
    transactionId: string;
    bridge: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receiver: string;
    minAmount: BigNumber;
    destinationChainId: BigNumber;
    hasSourceSwaps: boolean;
    hasDestinationCall: boolean;
  };
}

export declare namespace AcrossFacetV3 {
  export type AcrossV3DataStruct = {
    receiverAddress: PromiseOrValue<string>;
    refundAddress: PromiseOrValue<string>;
    receivingAssetId: PromiseOrValue<string>;
    outputAmount: PromiseOrValue<BigNumberish>;
    outputAmountPercent: PromiseOrValue<BigNumberish>;
    exclusiveRelayer: PromiseOrValue<string>;
    quoteTimestamp: PromiseOrValue<BigNumberish>;
    fillDeadline: PromiseOrValue<BigNumberish>;
    exclusivityDeadline: PromiseOrValue<BigNumberish>;
    message: PromiseOrValue<BytesLike>;
  };

  export type AcrossV3DataStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    number,
    number,
    number,
    string
  ] & {
    receiverAddress: string;
    refundAddress: string;
    receivingAssetId: string;
    outputAmount: BigNumber;
    outputAmountPercent: BigNumber;
    exclusiveRelayer: string;
    quoteTimestamp: number;
    fillDeadline: number;
    exclusivityDeadline: number;
    message: string;
  };
}

export declare namespace LibSwap {
  export type SwapDataStruct = {
    callTo: PromiseOrValue<string>;
    approveTo: PromiseOrValue<string>;
    sendingAssetId: PromiseOrValue<string>;
    receivingAssetId: PromiseOrValue<string>;
    fromAmount: PromiseOrValue<BigNumberish>;
    callData: PromiseOrValue<BytesLike>;
    requiresDeposit: PromiseOrValue<boolean>;
  };

  export type SwapDataStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber,
    string,
    boolean
  ] & {
    callTo: string;
    approveTo: string;
    sendingAssetId: string;
    receivingAssetId: string;
    fromAmount: BigNumber;
    callData: string;
    requiresDeposit: boolean;
  };
}

export interface AcrossFacetV3Interface extends utils.Interface {
  functions: {
    "spokePool()": FunctionFragment;
    "startBridgeTokensViaAcrossV3((bytes32,string,string,address,address,address,uint256,uint256,bool,bool),(address,address,address,uint256,uint64,address,uint32,uint32,uint32,bytes))": FunctionFragment;
    "swapAndStartBridgeTokensViaAcrossV3((bytes32,string,string,address,address,address,uint256,uint256,bool,bool),(address,address,address,address,uint256,bytes,bool)[],(address,address,address,uint256,uint64,address,uint32,uint32,uint32,bytes))": FunctionFragment;
    "wrappedNative()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "spokePool"
      | "startBridgeTokensViaAcrossV3"
      | "swapAndStartBridgeTokensViaAcrossV3"
      | "wrappedNative"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "spokePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startBridgeTokensViaAcrossV3",
    values: [ILiFi.BridgeDataStruct, AcrossFacetV3.AcrossV3DataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndStartBridgeTokensViaAcrossV3",
    values: [
      ILiFi.BridgeDataStruct,
      LibSwap.SwapDataStruct[],
      AcrossFacetV3.AcrossV3DataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedNative",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "spokePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startBridgeTokensViaAcrossV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndStartBridgeTokensViaAcrossV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedNative",
    data: BytesLike
  ): Result;

  events: {
    "BridgeToNonEVMChain(bytes32,uint256,bytes)": EventFragment;
    "BridgeToNonEVMChainBytes32(bytes32,uint256,bytes32)": EventFragment;
    "LiFiGenericSwapCompleted(bytes32,string,string,address,address,address,uint256,uint256)": EventFragment;
    "LiFiSwappedGeneric(bytes32,string,string,address,address,uint256,uint256)": EventFragment;
    "LiFiTransferCompleted(bytes32,address,address,uint256,uint256)": EventFragment;
    "LiFiTransferRecovered(bytes32,address,address,uint256,uint256)": EventFragment;
    "LiFiTransferStarted(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BridgeToNonEVMChain"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgeToNonEVMChainBytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiFiGenericSwapCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiFiSwappedGeneric"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiFiTransferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiFiTransferRecovered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiFiTransferStarted"): EventFragment;
}

export interface BridgeToNonEVMChainEventObject {
  transactionId: string;
  destinationChainId: BigNumber;
  receiver: string;
}
export type BridgeToNonEVMChainEvent = TypedEvent<
  [string, BigNumber, string],
  BridgeToNonEVMChainEventObject
>;

export type BridgeToNonEVMChainEventFilter =
  TypedEventFilter<BridgeToNonEVMChainEvent>;

export interface BridgeToNonEVMChainBytes32EventObject {
  transactionId: string;
  destinationChainId: BigNumber;
  receiver: string;
}
export type BridgeToNonEVMChainBytes32Event = TypedEvent<
  [string, BigNumber, string],
  BridgeToNonEVMChainBytes32EventObject
>;

export type BridgeToNonEVMChainBytes32EventFilter =
  TypedEventFilter<BridgeToNonEVMChainBytes32Event>;

export interface LiFiGenericSwapCompletedEventObject {
  transactionId: string;
  integrator: string;
  referrer: string;
  receiver: string;
  fromAssetId: string;
  toAssetId: string;
  fromAmount: BigNumber;
  toAmount: BigNumber;
}
export type LiFiGenericSwapCompletedEvent = TypedEvent<
  [string, string, string, string, string, string, BigNumber, BigNumber],
  LiFiGenericSwapCompletedEventObject
>;

export type LiFiGenericSwapCompletedEventFilter =
  TypedEventFilter<LiFiGenericSwapCompletedEvent>;

export interface LiFiSwappedGenericEventObject {
  transactionId: string;
  integrator: string;
  referrer: string;
  fromAssetId: string;
  toAssetId: string;
  fromAmount: BigNumber;
  toAmount: BigNumber;
}
export type LiFiSwappedGenericEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, BigNumber],
  LiFiSwappedGenericEventObject
>;

export type LiFiSwappedGenericEventFilter =
  TypedEventFilter<LiFiSwappedGenericEvent>;

export interface LiFiTransferCompletedEventObject {
  transactionId: string;
  receivingAssetId: string;
  receiver: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type LiFiTransferCompletedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  LiFiTransferCompletedEventObject
>;

export type LiFiTransferCompletedEventFilter =
  TypedEventFilter<LiFiTransferCompletedEvent>;

export interface LiFiTransferRecoveredEventObject {
  transactionId: string;
  receivingAssetId: string;
  receiver: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type LiFiTransferRecoveredEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  LiFiTransferRecoveredEventObject
>;

export type LiFiTransferRecoveredEventFilter =
  TypedEventFilter<LiFiTransferRecoveredEvent>;

export interface LiFiTransferStartedEventObject {
  bridgeData: ILiFi.BridgeDataStructOutput;
}
export type LiFiTransferStartedEvent = TypedEvent<
  [ILiFi.BridgeDataStructOutput],
  LiFiTransferStartedEventObject
>;

export type LiFiTransferStartedEventFilter =
  TypedEventFilter<LiFiTransferStartedEvent>;

export interface AcrossFacetV3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AcrossFacetV3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    spokePool(overrides?: CallOverrides): Promise<[string]>;

    startBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapAndStartBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _swapData: LibSwap.SwapDataStruct[],
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrappedNative(overrides?: CallOverrides): Promise<[string]>;
  };

  spokePool(overrides?: CallOverrides): Promise<string>;

  startBridgeTokensViaAcrossV3(
    _bridgeData: ILiFi.BridgeDataStruct,
    _acrossData: AcrossFacetV3.AcrossV3DataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapAndStartBridgeTokensViaAcrossV3(
    _bridgeData: ILiFi.BridgeDataStruct,
    _swapData: LibSwap.SwapDataStruct[],
    _acrossData: AcrossFacetV3.AcrossV3DataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrappedNative(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    spokePool(overrides?: CallOverrides): Promise<string>;

    startBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndStartBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _swapData: LibSwap.SwapDataStruct[],
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    wrappedNative(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "BridgeToNonEVMChain(bytes32,uint256,bytes)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      destinationChainId?: PromiseOrValue<BigNumberish> | null,
      receiver?: null
    ): BridgeToNonEVMChainEventFilter;
    BridgeToNonEVMChain(
      transactionId?: PromiseOrValue<BytesLike> | null,
      destinationChainId?: PromiseOrValue<BigNumberish> | null,
      receiver?: null
    ): BridgeToNonEVMChainEventFilter;

    "BridgeToNonEVMChainBytes32(bytes32,uint256,bytes32)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      destinationChainId?: PromiseOrValue<BigNumberish> | null,
      receiver?: null
    ): BridgeToNonEVMChainBytes32EventFilter;
    BridgeToNonEVMChainBytes32(
      transactionId?: PromiseOrValue<BytesLike> | null,
      destinationChainId?: PromiseOrValue<BigNumberish> | null,
      receiver?: null
    ): BridgeToNonEVMChainBytes32EventFilter;

    "LiFiGenericSwapCompleted(bytes32,string,string,address,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      receiver?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): LiFiGenericSwapCompletedEventFilter;
    LiFiGenericSwapCompleted(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      receiver?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): LiFiGenericSwapCompletedEventFilter;

    "LiFiSwappedGeneric(bytes32,string,string,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): LiFiSwappedGenericEventFilter;
    LiFiSwappedGeneric(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): LiFiSwappedGenericEventFilter;

    "LiFiTransferCompleted(bytes32,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): LiFiTransferCompletedEventFilter;
    LiFiTransferCompleted(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): LiFiTransferCompletedEventFilter;

    "LiFiTransferRecovered(bytes32,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): LiFiTransferRecoveredEventFilter;
    LiFiTransferRecovered(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): LiFiTransferRecoveredEventFilter;

    "LiFiTransferStarted(tuple)"(
      bridgeData?: null
    ): LiFiTransferStartedEventFilter;
    LiFiTransferStarted(bridgeData?: null): LiFiTransferStartedEventFilter;
  };

  estimateGas: {
    spokePool(overrides?: CallOverrides): Promise<BigNumber>;

    startBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapAndStartBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _swapData: LibSwap.SwapDataStruct[],
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrappedNative(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    spokePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapAndStartBridgeTokensViaAcrossV3(
      _bridgeData: ILiFi.BridgeDataStruct,
      _swapData: LibSwap.SwapDataStruct[],
      _acrossData: AcrossFacetV3.AcrossV3DataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrappedNative(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
